package ar.edu.unlu.parade.enumerados;

import java.io.Serializable;

public enum Opcion implements Serializable {
    CREACION_ARCHIVO,
    MENU_TURNO,
    MENU_TURNO_FINAL,
    SELECICON_EVALUAR,
    SELECICON_DESCARTAR,
    RANKING,
    HABILITAR_SALIR,
    MOSTRAR_AREA,
    MOSTRAR_AREA_TODOS,
    MOSTRAR_MANO,
    MOSTRAR_DESFILE,
    GANADOR_PARTIDA,
    EMPATE_JUGADORES,
    DESCARTE_Y_FINAL,
    MENSAJE_GUARDAR_Y_SALIR,
    GUARDAR_Y_SALIR,
    ACTUALIZAR_JUGADOR

}
