package ar.edu.unlu.parade.enumerados;

import java.io.Serializable;

public enum Opcion implements Serializable {
    MENU_PRINCIPAL,
    REGLAS,
    HISTORICO,
    TOP5,
    CREACION_ARCHIVO,
    SETEO_PARTIDA,
    MENU_TURNO,
    MENU_TURNO_FINAL,
    ADD_NOMBRE,
    SELECICON_EVALUAR,
    SELECICON_DESCARTAR,
    RANKING,
    HABILITAR_SALIR,
    MOSTRAR_AREA,
    MOSTRAR_AREA_TODOS,
    MOSTRAR_MANO,
    MOSTRAR_DESFILE,
    GANADOR_PARTIDA,
    EMPATE_JUGADORES,
    DESCARTE_Y_FINAL,
    ULTIMO_TURNO,
    MENSAJE_GUARDAR_Y_SALIR,
    GUARDAR_Y_SALIR,
    CARGAR_PARTIDA,
    ACTUALIZAR_TURNO,
    ACTUALIZAR_JUGADOR

}
